# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  name: AzureLocalPool

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $VersionRegex = "\d+\.\d+\.\d+\.\d+"
      $NewVersion = [regex]::matches($Env:BUILD_BUILDNUMBER,$VersionRegex)
      
      Write-Host "Updating version of the application to the build version: " $NewVersion
      $file = ".\AssemblyInfo.cs" 
      $filecontent = Get-Content($file)
      attrib $file -r
      
      # correct version number
      $filecontent -replace $VersionRegex, $NewVersion | Out-File $file
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: '$(System.TeamProject)-$(Build.BuildNumber)'
    publishLocation: 'Filepath'
    TargetPath: 'C:\Artifact'